services:
  spring-app-prod:
    build: .
    container_name: spring-app-prod
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env
    working_dir: /app
    ports:
      - "8080:8080"
    networks:
      - public_network

networks:
  public_network:
    driver: bridge

