services:
  spring-app:
    build: .
    container_name: spring-app
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - public_network

networks:
  public_network:
    driver: bridge

